name = "ze-worker-for-static-upload"
main = "src/index.ts"
compatibility_date = "2023-10-02"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
JWT_SECRET='{"kty":"RSA","n":"m8vGG3CptgdVkGa2AVpyaGXthIo6Qpaa0ey4V2Ui20Z6CyWzdSeLO0CL9NX611UKtpCRQM0X9LDj_-HQ4atsPCawW5hpdAzYq1hCeyUss_A3yfmLRlw5xa2rXN5X_c6VIf8i-ae8lEIIp9FruJ7psZl3lbEDCBv-edzhlVR4ZufyRuEOh0jQBU0Z5M3GiVikaWCQ2OSsFs5usZCf6FG0iVEEQosj03r9zE3qgtvf_hs7uj1j_o-Rbom4vVVIQm5vBKA2FNvDFEZRZZfwegFXN26rfIhe0IrRNbBhyMPMNu7caNVT-eeAY0VWZLzSC7QGIoTmf5uj7nrBkRqiBeYSWQ","e":"AQAB"}'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

 [[kv_namespaces]]
 binding = "ze_envs"
 id = "caea45f912c24e4887423422b52a877c"

 [[kv_namespaces]]
 binding = "ze_snapshots"
 id = "bfbebd5c4d724a6aa80510b9e43c61b1"

 [[kv_namespaces]]
 binding = "ze_files"
 id = "962f0549087e457bb32e9675bf65aa37"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[r2_buckets]]
# binding = "ze_r2_files"
# bucket_name = "ze-files"
#
# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/queues/get-started
# [[queues.consumers]]
# queue = "my-queue"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/platform/services
# [[services]]
# binding = "MY_SERVICE"
# service = "/api/*"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
# [[migrations]]
# tag = "v1"
# new_classes = ["MyDurableObject"]
